version: "2"
services:
  cli:
    build: ./cli
    command: ["/bin/sleep", "infinity"]
    image: storj-cli
  db:
    image: mongo:3.4.0
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27017:27017
  mq:
    image: rabbitmq:3.6.6
  bridge:
    build: ./bridge
    volumes:
      - ./bridge/bridge.config.json:/root/config.json
    command: ["./bin/storj-bridge.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=db:27017
    ports:
      - 8080:8080
  landlord:
    build: ./complex
    volumes:
      - ./complex/landlord.config.json:/root/config.template.json
    command: ["./bin/storj-complex.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=bridge:8080,db:27017,mq:5672
  renter:
    build: ./complex
    volumes:
      - ./complex/renter.config.json:/root/config.template.json
      - ./complex/hd-private.key:/root/hd-private.key
    command: ["./bin/storj-complex.js", "-c", "/root/config.json"]
    environment:
      - DOCKER_SERVICES=bridge:8080,db:27017,mq:5672
    restart: always
  share:
    build: ./share
    volumes:
      - ./share/data:/root/.storjshare
      - ./share/share.config.json:/root/.storjshare/config.template.json
    environment:
      - DOCKER_SERVICES=renter:4000
      - affinity:container!=/cadvisor/
    #ports:
    #  - 9000:9000
  proxy:
    build: ./vpn
    ports:
      - "127.0.0.1:13194:13194"
    command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194
  openvpn:
    build: ./vpn/openvpn
    #command: ["/bin/sleep", "6000"]
    volumes:
      - ./vpn:/local
      - ./vpn/config:/etc/openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      dest: docker-for-mac.ovpn
      DEBUG: '1'
    command: ["/local/helpers/run.sh"]

